--- 
javascripts: 
- base: 
  - jquery.min
  - jquery.lightbox-0.5
  - jScrollPane
  - jScrollHorizontalPane
  - jquery.textshadow
  - jquery.simplemodal-1.3.5
  - jquery.scrollTo-1.4.2-min
  - jquery.nivo.slider
  - jquery.mousewheel
  - jquery.example.min
  - jquery.em
  - jquery.dimensions
  - jquery.columnview
  - taxonomicbrowser
  - rails
  - application
- landscapes_maps:
  - OpenLayers
  - LandscapeMarker
  - landscapes_map
  - Icon
  - Marker
- species_maps:
  - OpenLayers
  - LandscapeMarker
  - specie_map
  - Icon
  - Marker  
- guides_maps:
  - OpenLayers
  - LandscapeMarker
  - guide_map
  - Icon
  - Marker  
  
stylesheets: 
- base: 
  - jquery.lightbox-0.5
  - jScrollPane
  - layout
  - scrollbars
