development:
  adapter: postgresql
  template: template_postgis
  encoding: unicode
  database: afg_development
  username: postgres
  password:

test:
  adapter: postgresql
  template: template_postgis
  encoding: unicode
  database: afg_test
  username: postgres
  password:

production:
  adapter: postgresql
  template: template_postgis
  encoding: unicode
  database: afg_production
  username: postgres
  password:
  